### ISSUE TITLE
Feature: Encryption support

### ISSUE THREAD

**Issue by zanets** [hiro0218/Miikun#15]
Hi, sorry I can't speak Japanese, but I will try to explain.

Since I write notes with markdown which related to my job, sometimes they contain sensitive information, that should not be exposed to any third party. I still want to use google drive to sync my notes within all my devices, so a local markdown editor with encryption support is the only way.

The most possible editor I can use is [Laverna](https://github.com/Laverna/laverna), but it doesn't support google drive and local storage is hard to use and lack of documentation. I once try to write a google drive plugin for it, but lacking of documentation and backbone.js made me headache.

And then I found this. Vue.js is not hard for me, I can implement those features I want. Actually, **I have implemented it, please see [my fork](https://github.com/darg20127/miikun).** 

I am not sure if you like this feature or not, so I open an issue to let you know it. I'd love to open a pull request and help to maintain this project.

**Comment by hiro0218** [comment]
@darg20127 

I saw your fork.

Excellent. Support for encrypted files is what I wanted. 
This is interesting to me.

Please make a pull request!
I will review it!

**Comment by hiro0218** [comment]
#16
