### ISSUE TITLE
ReferenceError: _construct is not defined when raise an error

### ISSUE THREAD

**Issue by zanets** [hiro0218/Miikun#25]
When raise an error, such as DecryptFailError, will shows 

> ReferenceError: _construct is not defined

This is a known issue from babel/runtime. See [Babel #8061](https://github.com/babel/babel/issues/8061). The solution is online, just waiting for babel merging.

I will do a workaround, please leave this issue open util babel solved it. Thanks.

**Comment by zanets** [comment]
Well, maybe add an upstream label or something is a good idea : )

**Comment by hiro0218** [comment]
Oh, I'm sorry. There was a lack of confirmation in my verification.

Thank you for creating your Pull Request.

**Comment by zanets** [comment]
Ha, its fine. Just a litle scared and WTF when I see this error but I couldn't find any wrong of our code.

Don't worry. I will handle this. Just do what you want : )

**Comment by zanets** [comment]
By the way, do you mind I write module with class like Errors.js? Since the environment allows it, and I think class can let the code looks clear.

It's OK if you don't like it and prefer others : )

**Comment by hiro0218** [comment]
Thanks a lot. Your work will help me.

I like class syntax. We will also use the class syntax as necessary in the future. 
So, your class syntax is okay 😊
